<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0" os="" host="USSERCELY07"><DocLocation><![CDATA[C:\Users\sercely\something\rpa]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[rpa]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:42]]></Time>
<TimeTick>1589893302</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;"StartUp&nbsp;Browser"&nbsp;object's&nbsp;description&nbsp;matches&nbsp;more&nbsp;than&nbsp;one&nbsp;of&nbsp;the&nbsp;objects&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.&nbsp;Add&nbsp;additional&nbsp;properties&nbsp;to&nbsp;the&nbsp;object&nbsp;description&nbsp;in&nbsp;order&nbsp;to&nbsp;uniquely&nbsp;identify&nbsp;the&nbsp;object.]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:42]]></Time>
<TimeTick>1589893302</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:42]]></Time>
<TimeTick>1589893302</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Warning" nType="Description" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Warning" nType="Run Error" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="10" status="Warning" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SpeakersCategoryTxt.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SpeakersCategoryTxt.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("SpeakersCategoryTxt")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Bose Soundlink Bluetooth.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Bose Soundlink Bluetooth.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Bose Soundlink Bluetooth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" Source="Action1" SourceLine="2" >
<Disp><![CDATA[quantity.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("quantity")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:43]]></Time>
<TimeTick>1589893303</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="27" Source="Action1" SourceLine="4" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save to cart")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:44]]></Time>
<TimeTick>1589893304</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="Action1" SourceLine="5" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("WebElement 2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HOME.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:44]]></Time>
<TimeTick>1589893304</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="Action1" SourceLine="6" >
<Disp><![CDATA[HOME.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("HOME")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="17" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="16" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[397892]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="5/19/2020 - 8:01:42" eTime="5/19/2020 - 8:01:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="13" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[Contact Us]]></AName>
<Summary sTime="5/19/2020 - 8:01:44" eTime="5/19/2020 - 8:01:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="35" >
<Disp><![CDATA[Contact Us Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[score]]></AName>
<Summary sTime="5/19/2020 - 8:01:44" eTime="5/19/2020 - 8:01:44" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="37" >
<Disp><![CDATA[score Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[rpa Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T18" iterID="2" >
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:44]]></Time>
<TimeTick>1589893304</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;"StartUp&nbsp;Browser"&nbsp;object's&nbsp;description&nbsp;matches&nbsp;more&nbsp;than&nbsp;one&nbsp;of&nbsp;the&nbsp;objects&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.&nbsp;Add&nbsp;additional&nbsp;properties&nbsp;to&nbsp;the&nbsp;object&nbsp;description&nbsp;in&nbsp;order&nbsp;to&nbsp;uniquely&nbsp;identify&nbsp;the&nbsp;object.]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:44]]></Time>
<TimeTick>1589893304</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:44]]></Time>
<TimeTick>1589893304</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="46" status="Warning" nType="Description" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="45" status="Warning" nType="Run Error" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="44" status="Warning" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T22">
<AName><![CDATA[Action1]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:45]]></Time>
<TimeTick>1589893305</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:45]]></Time>
<TimeTick>1589893305</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SpeakersCategoryTxt.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:45]]></Time>
<TimeTick>1589893305</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SpeakersCategoryTxt.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("SpeakersCategoryTxt")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Bose Soundlink Bluetooth.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:45]]></Time>
<TimeTick>1589893305</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Bose Soundlink Bluetooth.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Bose Soundlink Bluetooth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3"]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" Source="Action1" SourceLine="2" >
<Disp><![CDATA[quantity.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("quantity")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="61" Source="Action1" SourceLine="4" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save to cart")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="Action1" SourceLine="5" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("WebElement 2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[HOME.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="Action1" SourceLine="6" >
<Disp><![CDATA[HOME.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("HOME")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="50" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[397892]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="5/19/2020 - 8:01:45" eTime="5/19/2020 - 8:01:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="47" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[Contact Us]]></AName>
<Summary sTime="5/19/2020 - 8:01:46" eTime="5/19/2020 - 8:01:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="69" >
<Disp><![CDATA[Contact Us Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T32">
<AName><![CDATA[score]]></AName>
<Summary sTime="5/19/2020 - 8:01:46" eTime="5/19/2020 - 8:01:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="71" >
<Disp><![CDATA[score Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="40" status="Warning" >
<Disp><![CDATA[rpa Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T33" iterID="3" >
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;"StartUp&nbsp;Browser"&nbsp;object's&nbsp;description&nbsp;matches&nbsp;more&nbsp;than&nbsp;one&nbsp;of&nbsp;the&nbsp;objects&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.&nbsp;Add&nbsp;additional&nbsp;properties&nbsp;to&nbsp;the&nbsp;object&nbsp;description&nbsp;in&nbsp;order&nbsp;to&nbsp;uniquely&nbsp;identify&nbsp;the&nbsp;object.]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:46]]></Time>
<TimeTick>1589893306</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="80" status="Warning" nType="Description" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="79" status="Warning" nType="Run Error" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="78" status="Warning" Source="Action0" SourceLine="2" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T37">
<AName><![CDATA[Action1]]></AName>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:47]]></Time>
<TimeTick>1589893307</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:47]]></Time>
<TimeTick>1589893307</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SpeakersCategoryTxt.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:47]]></Time>
<TimeTick>1589893307</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SpeakersCategoryTxt.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("SpeakersCategoryTxt")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Bose Soundlink Bluetooth.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:47]]></Time>
<TimeTick>1589893307</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="89" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Bose Soundlink Bluetooth.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Bose Soundlink Bluetooth")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["4"]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:48]]></Time>
<TimeTick>1589893308</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="92" Source="Action1" SourceLine="2" >
<Disp><![CDATA[quantity.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("quantity")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:48]]></Time>
<TimeTick>1589893308</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="95" Source="Action1" SourceLine="4" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save to cart")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:48]]></Time>
<TimeTick>1589893308</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="98" Source="Action1" SourceLine="5" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("WebElement 2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[HOME.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/19/2020 - 8:01:48]]></Time>
<TimeTick>1589893308</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" Source="Action1" SourceLine="6" >
<Disp><![CDATA[HOME.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping").Link("HOME")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="85" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Advantage Shopping").Page("Advantage Shopping")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="84" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[397892]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="5/19/2020 - 8:01:47" eTime="5/19/2020 - 8:01:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="81" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T46">
<AName><![CDATA[Contact Us]]></AName>
<Summary sTime="5/19/2020 - 8:01:48" eTime="5/19/2020 - 8:01:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="103" >
<Disp><![CDATA[Contact Us Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T47">
<AName><![CDATA[score]]></AName>
<Summary sTime="5/19/2020 - 8:01:48" eTime="5/19/2020 - 8:01:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="6" nRep="105" >
<Disp><![CDATA[score Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="74" status="Warning" >
<Disp><![CDATA[rpa Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="5/19/2020 - 8:01:41" eTime="5/19/2020 - 8:01:48" passed="0" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test rpa Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>